language: node_js
node_js:
  - "7"

dist: trusty
sudo: false
group: edge

addons:
  sonarcloud:
    organization: "chowanioksource"
    branches :
      - develop
      - master

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
